# Generated by Django 5.1.2 on 2025-04-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0019_remove_botevent_valid_event_type_event_sub_type_combinations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='file_name',
            field=models.CharField(default='vanya-file-name', max_length=255),
        ),
    ]
