# Generated by Django 5.1.2 on 2025-07-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0020_recording_file_name'),
        ('bots', '0026_alter_bot_state_alter_botevent_event_type_and_more'),
    ]

    operations = [
    ]
