# Generated by Django 5.1.14 on 2026-02-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0075_alter_botmediarequest_loop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantevent',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Join'), (2, 'Leave'), (3, 'Speech Start'), (4, 'Speech Stop'), (5, 'Update')]),
        ),
        migrations.AlterField(
            model_name='webhookdeliveryattempt',
            name='webhook_trigger_type',
            field=models.IntegerField(choices=[(1, 'Bot State Change'), (2, 'Transcript Update'), (3, 'Chat Messages Update'), (4, 'Participant Join/Leave'), (5, 'Calendar Events Update'), (6, 'Calendar State Change'), (7, 'Async Transcription State Change'), (8, 'Zoom OAuth Connection State Change'), (9, 'Bot Logs Update'), (10, 'Participant Speech Start/Stop')], default=1),
        ),
    ]
