# Generated by Django 5.1.14 on 2026-03-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0077_alter_participantevent_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="output_file_defaults",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="project",
            name="transcription_defaults",
            field=models.JSONField(default=dict),
        ),
    ]
