# Generated by Django 5.1.14 on 2026-03-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0079_remove_botevent_valid_event_type_event_sub_type_combinations_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoogleMeetBotLogin',
            new_name='BotLogin',
        ),
        migrations.RenameModel(
            old_name='GoogleMeetBotLoginGroup',
            new_name='BotLoginGroup',
        ),
        migrations.AlterModelTable(
            name='botlogin',
            table='bots_googlemeetbotlogin',
        ),
        migrations.AlterModelTable(
            name='botlogingroup',
            table='bots_googlemeetbotlogingroup',
        ),
    ]
