# Generated by Django 5.1.14 on 2026-03-30 18:12

import json
from cryptography.fernet import Fernet
from django.conf import settings
from django.db import migrations, models


TEAMS_BOT_LOGIN_CREDENTIAL_TYPE = 8


def backfill_teams_bot_logins(apps, schema_editor):
    BotLogin = apps.get_model("bots", "BotLogin")
    BotLoginGroup = apps.get_model("bots", "BotLoginGroup")
    Credentials = apps.get_model("bots", "Credentials")
    f = Fernet(settings.CREDENTIALS_ENCRYPTION_KEY)

    for credential in Credentials.objects.filter(credential_type=TEAMS_BOT_LOGIN_CREDENTIAL_TYPE):
        if not credential._encrypted_data:
            continue

        decrypted_data = f.decrypt(bytes(credential._encrypted_data))
        credentials_dict = json.loads(decrypted_data.decode())
        username = credentials_dict.get("username")
        password = credentials_dict.get("password")

        if not username or not password:
            continue

        bot_login_group, created = BotLoginGroup.objects.get_or_create(
            project=credential.project,
            platform="teams",
            name="Teams Group 1",
        )

        bot_login = BotLogin.objects.create(
            group=bot_login_group,
            email=username,
        )
        bot_login._encrypted_data = f.encrypt(json.dumps({"password": password}).encode())
        bot_login.save(update_fields=["_encrypted_data"])

class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0081_backfill_botlogingroup_and_botlogin_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_teams_bot_logins, reverse_code=migrations.RunPython.noop),
    ]
