# Generated by Django 5.1.14 on 2026-03-30 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0082_rename_googlemeetbotlogin_botlogin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botlogingroup',
            name='name',
            field=models.CharField(max_length=255, default='Google Meet Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botlogingroup',
            name='platform',
            field=models.CharField(choices=[('google_meet', 'Google Meet'), ('teams', 'Teams')], max_length=32, default='google_meet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botlogin',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_logins', to='bots.botlogingroup'),
        ),
        migrations.AlterField(
            model_name='botlogin',
            name='workspace_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='botlogingroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_login_groups', to='bots.project'),
        ),
        migrations.AddConstraint(
            model_name='botlogingroup',
            constraint=models.UniqueConstraint(fields=('project', 'platform', 'name'), name='unique_bot_login_group_project_platform_name'),
        ),
        migrations.RemoveConstraint(
            model_name='botlogin',
            name='unique_google_meet_bot_login_email',
        ),
        migrations.AddConstraint(
            model_name='botlogin',
            constraint=models.UniqueConstraint(fields=('group', 'email'), name='unique_bot_login_email_per_group'),
        ),
    ]
