# Generated by Django 5.1.14 on 2026-08-17 23:56

import concurrency.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0088_alter_credentials_credential_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='session_type',
            field=models.IntegerField(choices=[(1, 'Bot'), (2, 'App Session'), (3, 'Desktop Recording')], db_default=1, default=1),
        ),
        migrations.CreateModel(
            name='RecorderUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('state', models.IntegerField(choices=[(1, 'Created'), (2, 'Uploading'), (3, 'Uploaded'), (4, 'Complete'), (5, 'Failed'), (6, 'Expired')], default=1)),
                ('s3_key', models.CharField(max_length=1024)),
                ('upload_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('content_type', models.CharField(max_length=255)),
                ('bytes_expected', models.BigIntegerField(blank=True, null=True)),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('parts', models.JSONField(default=list)),
                ('failure_data', models.JSONField(blank=True, null=True)),
                ('deduplication_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recorder_upload', to='bots.bot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorder_uploads', to='bots.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(models.Q(('state__in', [4, 5, 6]), _negated=True), ('deduplication_key__isnull', False)), fields=('project', 'deduplication_key'), name='unique_recorder_upload_deduplication_key')],
            },
        ),
    ]
