# Generated by Django 5.2.17 on 2026-09-15 01:50

from django.db import migrations
from django.db.models import Count


def delete_duplicate_project_accesses(apps, schema_editor):
    ProjectAccess = apps.get_model('bots', 'ProjectAccess')

    duplicated_pairs = ProjectAccess.objects.values('project', 'user').annotate(access_count=Count('id')).filter(access_count__gt=1)

    for pair in duplicated_pairs:
        access_ids = list(ProjectAccess.objects.filter(project=pair['project'], user=pair['user']).order_by('-id').values_list('id', flat=True))

        # The highest id was written last, so it reflects the most recent intent
        ids_to_delete = access_ids[1:]
        ProjectAccess.objects.filter(id__in=ids_to_delete).delete()
        print(f"Deleted {len(ids_to_delete)} duplicate project accesses for project {pair['project']} and user {pair['user']}, kept {access_ids[0]}")


def reverse_deletion(apps, schema_editor):
    # No reverse operation - the deleted duplicates cannot be restored
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0091_alter_credentials_credential_type'),
    ]

    operations = [
        migrations.RunPython(delete_duplicate_project_accesses, reverse_deletion),
    ]
