# Generated by Django 5.2.17 on 2026-09-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0091_alter_credentials_credential_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaccess',
            name='can_manage_api_keys',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='projectaccess',
            name='can_view_recording_content',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
