# Generated by Django 5.2.17 on 2026-09-15 01:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0092_backfill_delete_duplicate_project_accesses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaccess',
            name='can_manage_api_keys',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='projectaccess',
            name='can_view_recording_content',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddConstraint(
            model_name='projectaccess',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_access_project_user'),
        ),
    ]
