# Generated by Django 5.2.17 on 2026-09-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0092_projectaccess_can_manage_api_keys_and_more'),
    ]

    operations = [
    ]
