apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager
  namespace: attendee
  labels:
    app.kubernetes.io/name: "attendee"
    app.kubernetes.io/managed-by: cuber
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager-binding
  namespace: attendee
  labels:
    app.kubernetes.io/name: "attendee"
    app.kubernetes.io/managed-by: cuber
subjects:
- kind: ServiceAccount
  name: default
  namespace: attendee
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
