# Generated by hand for notifications isolated app
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["key"]},
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("sender_user_id", models.CharField(blank=True, default="", max_length=64)),
                ("source_service", models.CharField(blank=True, default="", max_length=200)),
                ("title", models.CharField(max_length=500)),
                ("body", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("priority", models.CharField(choices=[("low", "Low"), ("normal", "Normal"), ("high", "High"), ("urgent", "Urgent")], default="normal", max_length=10)),
                ("channels", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notifications", to="notifications.notificationcategory")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TeamNotificationPreference",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("team_id", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="team_preferences", to="notifications.notificationcategory")),
            ],
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="user_preferences", to="notifications.notificationcategory")),
            ],
        ),
        migrations.CreateModel(
            name="NotificationRecipient",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("recipient_sub", models.CharField(db_index=True, max_length=64)),
                ("recipient_type", models.CharField(choices=[("user", "User"), ("group", "Group"), ("team", "Team")], default="user", max_length=20)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notification", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recipients", to="notifications.notification")),
            ],
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(fields=["recipient_sub", "is_read"], name="notifications_recipient_sub_is_read_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(fields=["recipient_sub", "created_at"], name="notifications_recipient_sub_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="notificationrecipient",
            constraint=models.UniqueConstraint(fields=("notification", "recipient_sub"), name="notifications_uniq_notification_recipient"),
        ),
        migrations.AddConstraint(
            model_name="teamnotificationpreference",
            constraint=models.UniqueConstraint(condition=models.Q(("category__isnull", False)), fields=("team_id", "category"), name="notifications_uniq_team_pref"),
        ),
        migrations.AddConstraint(
            model_name="teamnotificationpreference",
            constraint=models.UniqueConstraint(condition=models.Q(("category__isnull", True)), fields=("team_id",), name="notifications_uniq_team_block_all"),
        ),
        migrations.AddConstraint(
            model_name="usernotificationpreference",
            constraint=models.UniqueConstraint(condition=models.Q(("category__isnull", False)), fields=("user_id", "category"), name="notifications_uniq_user_pref"),
        ),
        migrations.AddConstraint(
            model_name="usernotificationpreference",
            constraint=models.UniqueConstraint(condition=models.Q(("category__isnull", True)), fields=("user_id",), name="notifications_uniq_user_block_all"),
        ),
    ]
